-- SmartEdu Database Schema for MySQL

CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS students (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  date_of_birth DATE NULL,
  enrollment_date DATE NOT NULL,
  phone VARCHAR(255) NULL,
  address VARCHAR(255) NULL,
  user_id BIGINT UNIQUE NULL,
  email VARCHAR(255) NULL,
  username VARCHAR(255) NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL,
  status VARCHAR(50) NOT NULL,
  approval_status VARCHAR(20) NOT NULL DEFAULT 'APPROVED',
  student_id BIGINT NOT NULL,
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS marks (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  subject VARCHAR(255) NOT NULL,
  marks_obtained DOUBLE NOT NULL,
  total_marks DOUBLE NOT NULL,
  grade VARCHAR(5) NULL,
  approval_status VARCHAR(20) NOT NULL DEFAULT 'APPROVED',
  student_id BIGINT NOT NULL,
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  message VARCHAR(500) NOT NULL,
  timestamp DATETIME NOT NULL,
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  user_id BIGINT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
